//
//  pendulumODE.java
//
//  System definition file for the vector field named: pendulum
//
//  This file was generated by the program VFGEN, version: 2.6.0.dev2
//  Generated on 19-Mar-2022 at 18:36
//

package pendulumODE;

import org.apache.commons.math3.ode.FirstOrderDifferentialEquations;
import static java.lang.Math.*;

public class pendulumODE implements FirstOrderDifferentialEquations {

    private double g, b, L, m;

    public pendulumODE(double g, double b, double L, double m) {
        this.g = g;
        this.b = b;
        this.L = L;
        this.m = m;
    }

    public pendulumODE() {
        g = 9.8100000000000005e+00;
        b = 0.0000000000000000e+00;
        L = 1.0000000000000000e+00;
        m = 1.0000000000000000e+00;
    }

    public int getDimension() {
        return 2;
    }

    //
    //  The vector field.
    //
    public void computeDerivatives(double t, double[] state, double[] deriv) {
        double Pi = PI;
        double theta      = state[0];
        double v          = state[1];

        deriv[0] = v;
        deriv[1] = -b/(L*L)*v/m-sin(theta)/L*g;
    }
}

