# Makefile for pendulum_demo

OBJFILES = pendulum_demo.o pendulum_vf.o

pendulum_demo: $(OBJFILES)
	$(CXX) $(OBJFILES) $(LDFLAGS) -o $@

pendulum_demo.o: pendulum_demo.cpp pendulum_vf.h
	$(CXX) $(CXXFLAGS) -c pendulum_demo.cpp

pendulum_vf.o: pendulum_vf.cpp pendulum_vf.h
	$(CXX) $(CXXFLAGS) -c pendulum_vf.cpp
