//
//  pendulum_vf.cpp
//
//  Implementation for the vector field named: pendulum
//
//  This file was generated by the program VFGEN, version: 2.6.0.dev2
//  Generated on 27-Feb-2022 at 22:42
//

#include <cmath>
#include "pendulum_vf.h"

void pendulum_vf::operator()(const state_type &x_, state_type &dxdt_, const double t_)
{
    const double Pi = M_PI;
    double theta, v;

    theta      = x_[0];
    v          = x_[1];

    dxdt_[0] = v;
    dxdt_[1] = -1.0/(L*L)*v/m*b-1.0/L*g*sin(theta);
}

//
//  The Jacobian.
//

void pendulum_vf::jac(const state_type &x_, matrix_type &J_, const double &t_, state_type &dfdt_)
{
    const double Pi = M_PI;
    double theta, v;
    theta      = x_[0];
    v          = x_[1];
    J_(0, 0) = 0.0;
    J_(0, 1) = 1.0;
    J_(1, 0) = -1.0/L*g*cos(theta);
    J_(1, 1) = -1.0/(L*L)/m*b;
    dfdt_(0) = 0.0;
    dfdt_(1) = 0.0;
}
