//
//  pendulum_vf.cpp
//
//  Implementation for the vector field named: pendulum
//
//  This file was generated by the program VFGEN, version: 2.6.0.dev0
//  Generated on  4-Jun-2019 at 01:56
//

#include "pendulum_vf.h"

void pendulum_vf::pendulum_rhs(const state_type &x_, state_type &dxdt_, const double t_)
{
    const double Pi = M_PI;
    double theta, v;

    theta      = x_[0];
    v          = x_[1];

    dxdt_[0] = v;
    dxdt_[1] = -b/(L*L)*v/m-1.0/L*sin(theta)*g;
}

//
//  The Jacobian.
//

void pendulum_vf::pendulum_jac(const state_type &x_, matrix_type &J_, const double &t_, state_type &dfdt_)
{
    const double Pi = M_PI;
    double theta, v;
    theta      = x_[0];
    v          = x_[1];
    J_(0, 0) = 0.0;
    J_(0, 1) = 1.0;
    J_(1, 0) = -1.0/L*g*cos(theta);
    J_(1, 1) = -b/(L*L)/m;
    dfdt_(0) = 0.0;
    dfdt_(1) = 0.0;
}
