# This script runs the Makefile in each example directory
# (e.g. example_octave/Makefile).  Where possible, the Makefile
# generates *all* the example output that is used in the web page.
# That includes compiling and running the demo to generate plots or
# other outputs that are linked in the web page.  This currently
# isn't possible with all the commands; some require being run by
# hand or taking a screenshot to get a plot for the web page.
#
# The Makefiles have two targets for cleaning up:
#     make clean
#         Removes only the files that are not used in the web page (*.o,
#         executables, etc.).
#     make purge
#         Removes *everything* that is generated by the Makefile.
#
# To regenerate the web page data, in each directory run
#     make purge
#     make
#     make clean
#
# DONE (two clean up targets, 'clean' and 'purge'):
#     adolc
#     auto
#     check
#     cvode
#     dde_solver
#     dde23 [1]
#     ddebiftool [1]
#     delay2ode
#     evf
#     gsl
#     help (nothing to do)
#     javascript
#     latex
#     lsoda
#     matcont [1]
#     matlab [1]
#     octave
#     pydstool
#     pygsl
#     r [4]
#     radau5
#     scilab [3]
#     scipy
#     taylor
#     xpp [2]
#
# [1] The Matlab plots and screenshots are not generated by the Makefile.
#     Don't delete the PNG files!
# [2] The XPP screenshots are not generated by the Makefile.
#     The XPP screenshot should be regenerated with the latest version of XPP.
# [3] The scilab screenshot is not generated by the Makefile.
# [4] The R plots are not generated by the Makefile.
#

echo "Making example files:"

for name in `/bin/ls -1 -d example_*`; do
    if test ${name} != "example_vf"; then
        echo " " ${name}
        cd ${name}
        make -s purge
        make -s
        make -s clean
        cd ..
    fi
done

echo "DONE."
